batch_size: 50
data_dir: data/reacher_limited_batch7/smoothed
epochs: 4000
learning_rate: 0.001
log_dir: /data/max/tf-log/psse/reacher/highz/
seed: 4
state_embedding_hypers:
  KL_lambda: 0.5
  estimator_version: B
  increase_zhat_sigma: true
  learning_rate: 0.001
  z_dim: 10
  optimizer: adam
state_select:
- 0
- 1
- 4
- 5
state_shape:
- 4
steps:
- 1
- 3
- 5
- 10
- 30
time_select: 10
