type: ppo_cartpole
seed: 1
swingup: False
swingup_reward_version: 4
use_state_embedding: False
augment_embedded_state: False
model_dir: None

algo: PPO
algo_params:
  max_path_length: 100
  discount: 0.99
policy_hidden_sizes: [32, 32]
epochs: 1000
batch_size: 4000

