type: trpo_reacher_embedded_augment
use_state_embedding: True
augment_embedded_state: True
model_dir: '../models/reacher_limited/train_6'
env_params:
  obs_theta: True
  obs_trig: False
  obs_target: True
algo: TRPO
algo_params:
  max_path_length: 100
  discount: 0.99
  max_kl_step: 0.01
policy_hidden_sizes: [32, 32]
epochs: 2000
batch_size: 4000

