type: trpo_cartpole_embedded_augment_highz
seed: 1
swingup: False
swingup_reward_version: 4
use_state_embedding: True
augment_embedded_state: True
model_dir: '../models/cartpole/highz_train_0'

algo: TRPO
algo_params:
  discount: 0.99
  max_kl_step: 0.01
  max_path_length: 100
policy_hidden_sizes: [32, 32]
batch_size: 4000
epochs: 2000
